Repository rebellions-sw/vllm-rbln, pull requests merged in 2025-08, with the labels that each got.

#7 Support for flash attention
  examples/experimental/qwen3_flash_test.py
  vllm_rbln/attention/backends/flash_attention.py
  vllm_rbln/worker/model_runner.py
  vllm_rbln/worker/utils.py
  vllm_rbln/worker/worker.py
Labels: enhancement, torch.compile

#40 update(docs): update CONTRIBUTING and PR Template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#56 fix: use config classes when computing max blocks
  vllm_rbln/worker/utils.py
  vllm_rbln/worker/worker.py
Labels: torch.compile

#44 feat(model): update and refactor the sliding window attention
  vllm_rbln/model_executor/models/optimum/__init__.py
  vllm_rbln/model_executor/models/optimum/blip2.py
  vllm_rbln/model_executor/models/optimum/decoder_only.py
  vllm_rbln/model_executor/models/optimum/encoder_decoder.py
  vllm_rbln/model_executor/models/optimum/gemma3.py
  vllm_rbln/model_executor/models/optimum/idefics3.py
  vllm_rbln/model_executor/models/optimum/llava.py
  vllm_rbln/model_executor/models/optimum/llava_next.py
  vllm_rbln/model_executor/models/optimum/model_base.py
  vllm_rbln/model_executor/models/optimum/optimum_attention/__init__.py
  vllm_rbln/model_executor/models/optimum/optimum_attention/optimum_attention_manager.py
  vllm_rbln/model_executor/models/optimum/optimum_attention/optimum_attention_strategy.py
  vllm_rbln/model_executor/models/optimum/optimum_attention/utils.py
  vllm_rbln/model_executor/models/optimum/qwen2_5_vl.py
  vllm_rbln/model_executor/models/optimum/sliding_window.py
  vllm_rbln/model_executor/models/optimum/whisper.py
  vllm_rbln/v1/worker/optimum_model_runner.py
  vllm_rbln/worker/optimum_model_runner.py
Labels: enhancement, optimum

#59 fix(worker): clamp num available blocks by num required blocks
  vllm_rbln/worker/worker.py
Labels: torch.compile
